### PR TITLE
Fix screenshot

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by purcell** [comment]
This isn't my repo, sorry: it's just a fork. Please submit upstream.

**Comment by ShalokShalom** [comment]
Well, it seems to official repo is down.

**Comment by purcell** [comment]
Ah. I'm not going to maintain the theme myself, but I'd suggest the following:

1. Try to contact the author (whose email is in the .el file) and see if they are hosting the file elsewhere, or if they would allow you to take over its maintenance.
2. If the repo simply moved, then submit a change to the MELPA recipe. If you're going to take over maintenance, then fork this repo into your Github account and submit a MELPA recipe change.

**Comment by ShalokShalom** [comment]
Thanks. :)

**Pull request closed without merging**
